CREATE TABLE room_images (
  id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
  url VARCHAR(2048) NOT NULL,
  room_id VARCHAR(36) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,

  INDEX room_id (room_id),
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);
