version: "3.9"

services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 58000:8000
    depends_on:
      - surrealdb
      - test_surrealdb
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - 43000:3000
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - 48000:8000
    volumes:
      - surrealdb:/db
    command: start --log debug --user root --pass root file:/db/rent-bernard.db
  test_surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - 48001:8000
    command: start --log debug --user root --pass root memory
volumes:
  surrealdb:
