version: "3.9"

services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/rent-bernard"
    ports:
      - 58000:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - 43000:3000
  mysql:
    image: mysql:8
    ports:
      - 53306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "rent-bernard"
      MYSQL_ROOT_PASSWORD: "root"
volumes:
  mysql:
