version: "3.9"

services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 58000:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 43000:3000
