version: "3.9"

services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 58000:8000
    depends_on:
      - postgres
      - test_postgres
      - s3
    env_file:
      - ./api/.env.docker
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - 43000:3000
  postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rent_bernard
    ports:
      - 45432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  test_postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 45433:5432
  s3:
    build: ./docker/s3
    ports:
      - 44569:4569
    volumes:
      - s3:/app/buckets
      - ./docker/s3/serverless.yml:/app/serverless.yml
      - ./docker/s3/cors.xml:/app/cors.xml
volumes:
  postgres:
  s3:
