CREATE TABLE rooms (
  id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
  title VARCHAR(1024) NOT NULL,
  price BIGINT NOT NULL,
  area VARCHAR(1024) NOT NULL,
  street VARCHAR(1024),
  is_furnished BOOLEAN NOT NULL,
  is_pet_friendly BOOLEAN NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);
