name: api

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Containers
        run: docker compose up -d api test_postgres
      - name: Run tests
        run: docker exec $(docker ps | grep api | cut -d ' ' -f1) cargo test
      - name: Format
        run: |
          docker exec $(docker ps | grep api | cut -d ' ' -f1) rustup component add rustfmt
          docker exec $(docker ps | grep api | cut -d ' ' -f1) cargo fmt --all -- --check
      - name: Clippy
        run: |
          docker exec $(docker ps | grep api | cut -d ' ' -f1) rustup component add clippy
          docker exec $(docker ps | grep api | cut -d ' ' -f1) sqlx migrate run
          docker exec $(docker ps | grep api | cut -d ' ' -f1) cargo clippy
