name: api

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          docker compose up -d api test_surrealdb
          docker exec $(docker ps | grep api | cut -d ' ' -f1) cargo test
      - name: Clippy
        run: |
          docker exec $(docker ps | grep api | cut -d ' ' -f1) rustup component add clippy
          docker exec $(docker ps | grep api | cut -d ' ' -f1) cargo clippy --verbose -- -D warnings
