name: build-container

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Containers
        run: docker compose up -d api test_surrealdb
