name: frontend

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
    paths:
      - "frontend/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Containers
        run: docker compose up -d frontend
      - name: Install dependencies
        run: docker exec $(docker ps | grep frontend | cut -d ' ' -f1) npm install
      - name: Build
        run: docker exec $(docker ps | grep frontend | cut -d ' ' -f1) npm run build
      - name: ESLint
        run: docker exec $(docker ps | grep frontend | cut -d ' ' -f1) npm run lint
      - name: Prettier
        run: docker exec $(docker ps | grep frontend | cut -d ' ' -f1) npm run format
