name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-container:
    uses: ./.github/workflows/build-container.yml

  test:
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - uses: actions/checkout@v3
      # FIXME: It takes too much time to run tests
      # - name: Run tests
      #   run: docker exec $(docker ps | grep api | cut -d ' ' -f1) cargo test
      - name: Format
        run: |
          docker exec $(docker ps | grep api | cut -d ' ' -f1) rustup component add rustfmt
          docker exec $(docker ps | grep api | cut -d ' ' -f1) cargo fmt --all -- --check
      - name: Clippy
        run: |
          docker exec $(docker ps | grep api | cut -d ' ' -f1) rustup component add clippy
          docker exec $(docker ps | grep api | cut -d ' ' -f1) cargo clippy
